/**
 * BeBeautiful Test Cases Definition
 * Single source of truth for all TC metadata
 * Used by Excel report generator and test documentation
 */

module.exports = [
  // ─────────────────── HOMEPAGE (TC002, TC003, TC005, TC016) ─────────────────
  {
    id: 'TC002',
    module: 'Homepage',
    scenario: 'Verify banner video section',
    steps: [
      'Navigate to homepage',
      'Check banner video element visibility',
      'Verify pagination bullets are present',
      'Check Next Slide arrow button',
      'Click Next Slide and verify slide changes',
      'Check Dive In button in banner',
    ],
    expected: 'Banner video section loads with navigation controls and Dive In button',
    priority: 'P0',
  },
  {
    id: 'TC003',
    module: 'Homepage',
    scenario: 'Verify all links in menu section',
    steps: [
      'Navigate to homepage',
      'Verify header navigation is visible',
      'Count total navigation items in menu',
      'Click each menu link and verify navigation',
      'Verify site logo is present in header',
    ],
    expected: 'All menu links are functional with valid hrefs or submenus',
    priority: 'P0',
  },
  {
    id: 'TC005',
    module: 'Homepage',
    scenario: 'Search bar with valid keyword',
    steps: [
      'Navigate to homepage',
      'Locate search bar in header',
      'Enter valid search keyword (skincare)',
      'Submit search',
      'Verify search results page loads',
      'Verify results are relevant to search term',
    ],
    expected: 'Search returns relevant results for the entered keyword',
    priority: 'P0',
  },
  {
    id: 'TC016',
    module: 'Homepage',
    scenario: 'Verify article section',
    steps: [
      'Navigate to homepage',
      'Scroll to article section',
      'Verify article cards are displayed',
      'Check article category tabs',
      'Click on one article card',
      'Verify article page loads',
    ],
    expected: 'Article section displays articles with clickable cards',
    priority: 'P0',
  },

  // ─────────────────── BLOG PAGE (TC047, TC049-TC058) ────────────────────────
  {
    id: 'TC047',
    module: 'Blog Page',
    scenario: 'Article page header and basic details',
    steps: [
      'Navigate to an article page',
      'Verify article title is displayed',
      'Check article subtitle is visible',
      'Verify hero image is loaded',
      'Check author name and date',
    ],
    expected: 'Article header displays title, subtitle, image, author, and date',
    priority: 'P0',
  },
  {
    id: 'TC049',
    module: 'Blog Page',
    scenario: 'Share functionality',
    steps: [
      'Navigate to article page',
      'Locate share button',
      'Click share button',
      'Verify share popup opens',
      'Check social media icons (Instagram, WhatsApp, Mail, Twitter)',
      'Click on one social icon',
    ],
    expected: 'Share popup displays social media sharing options',
    priority: 'P0',
  },
  {
    id: 'TC050',
    module: 'Blog Page',
    scenario: 'Download and Listen Now options',
    steps: [
      'Navigate to article page',
      'Check for Download option',
      'Verify Listen Now button is visible',
      'Click Listen Now',
      'Verify audio player appears',
    ],
    expected: 'Article provides download and audio listening options',
    priority: 'P0',
  },
  {
    id: 'TC051',
    module: 'Blog Page',
    scenario: 'Keep Reading to Know section',
    steps: [
      'Navigate to article page',
      'Scroll to Keep Reading section',
      'Verify related articles are displayed',
      'Check if articles have titles and thumbnails',
      'Click on a related article',
    ],
    expected: 'Keep Reading section shows related articles',
    priority: 'P0',
  },
  {
    id: 'TC052',
    module: 'Blog Page',
    scenario: 'FAQ section',
    steps: [
      'Navigate to article page',
      'Scroll to FAQ section',
      'Verify FAQ items are displayed',
      'Click on FAQ accordion item',
      'Verify FAQ content expands',
    ],
    expected: 'FAQ section is visible with expandable accordion items',
    priority: 'P0',
  },
  {
    id: 'TC053',
    module: 'Blog Page',
    scenario: 'BePicks section on right',
    steps: [
      'Navigate to article page',
      'Verify BePicks section is visible',
      'Check product cards are displayed in BePicks',
      'Verify product images load',
      'Check View button on each product card',
    ],
    expected: 'BePicks section displays product recommendations',
    priority: 'P0',
  },
  {
    id: 'TC054',
    module: 'Blog Page',
    scenario: 'Going Viral section',
    steps: [
      'Navigate to article page',
      'Scroll to Going Viral section',
      'Verify trending articles are displayed',
      'Check article cards have images and titles',
      'Click on a trending article',
    ],
    expected: 'Going Viral section shows trending articles',
    priority: 'P0',
  },
  {
    id: 'TC055',
    module: 'Blog Page',
    scenario: 'Catalog section products',
    steps: [
      'Navigate to article page',
      'Scroll to Catalog section',
      'Verify product carousel is visible',
      'Check product cards are displayed',
      'Verify product images and titles load',
    ],
    expected: 'Catalog section displays product carousel',
    priority: 'P0',
  },
  {
    id: 'TC056',
    module: 'Blog Page',
    scenario: 'Also Your Vibe section',
    steps: [
      'Navigate to article page',
      'Scroll to Also Your Vibe section',
      'Verify section is visible',
      'Check articles are displayed',
      'Click on an article card',
    ],
    expected: 'Also Your Vibe section displays related articles',
    priority: 'P0',
  },
  {
    id: 'TC057',
    module: 'Blog Page',
    scenario: 'Dive In CTA navigation',
    steps: [
      'Navigate to article page',
      'Locate Dive In button',
      'Click Dive In button',
      'Verify navigation to relevant page',
    ],
    expected: 'Dive In CTA button navigates to relevant page',
    priority: 'P0',
  },
  {
    id: 'TC058',
    module: 'Blog Page',
    scenario: 'Article footer section',
    steps: [
      'Navigate to article page',
      'Scroll to footer',
      'Verify footer is visible',
      'Check footer links are present',
      'Verify social links are present',
    ],
    expected: 'Article footer displays links and social media options',
    priority: 'P0',
  },

  // ──────────────── BLOG LISTING PAGE (TC059-TC062) ──────────────────────────
  {
    id: 'TC059',
    module: 'Blog Listing Page',
    scenario: 'Article listing header and basic details',
    steps: [
      'Navigate to article listing page',
      'Verify page header is displayed',
      'Check breadcrumb navigation',
      'Verify marquee banner',
    ],
    expected: 'Article listing page displays proper header and navigation',
    priority: 'P0',
  },
  {
    id: 'TC060',
    module: 'Blog Listing Page',
    scenario: 'Article listing below marquee',
    steps: [
      'Navigate to article listing page',
      'Scroll below marquee',
      'Verify featured article is displayed',
      'Check article card has title and image',
      'Click on featured article',
    ],
    expected: 'Featured article is displayed below marquee',
    priority: 'P0',
  },
  {
    id: 'TC061',
    module: 'Blog Listing Page',
    scenario: 'People are looking for section',
    steps: [
      'Navigate to article listing page',
      'Scroll to People Looking For section',
      'Verify carousel is visible',
      'Check category cards are displayed',
      'Click on a category card',
    ],
    expected: 'People Looking For section shows category carousel',
    priority: 'P0',
  },
  {
    id: 'TC062',
    module: 'Blog Listing Page',
    scenario: 'All articles section',
    steps: [
      'Navigate to article listing page',
      'Scroll to All Articles section',
      'Verify article grid is displayed',
      'Check sort dropdown is present',
      'Verify Load More button appears',
    ],
    expected: 'All Articles section displays article grid with sort and load more',
    priority: 'P0',
  },

  // ──────────────────── LOGIN PAGE (TC070, TC071) ────────────────────────────
  {
    id: 'TC070',
    module: 'Login Page',
    scenario: 'Login page UI',
    steps: [
      'Navigate to login page',
      'Verify login banner is displayed',
      'Check Feels good text is present',
      'Verify mobile input field is visible',
      'Check Login button is present',
      'Verify Google and Facebook login options',
    ],
    expected: 'Login page displays all UI elements correctly',
    priority: 'P0',
  },
  {
    id: 'TC071',
    module: 'Login Page',
    scenario: 'Mobile number field validation',
    steps: [
      'Navigate to login page',
      'Click mobile number input field',
      'Enter invalid mobile number (less than 10 digits)',
      'Verify validation error is displayed',
      'Enter valid 10-digit mobile number',
      'Verify no validation error',
    ],
    expected: 'Mobile number field validates input format correctly',
    priority: 'P0',
  },

  // ──────────────── SIGNUP PAGE (TC074, TC075) ───────────────────────────────
  {
    id: 'TC074',
    module: 'Signup Page',
    scenario: 'Signup page UI',
    steps: [
      'Navigate to signup page',
      'Verify signup banner is displayed',
      'Check Let\'s get you started text',
      'Verify mobile input field is visible',
      'Check Signup button is present',
      'Verify Google and Facebook signup options',
    ],
    expected: 'Signup page displays all UI elements correctly',
    priority: 'P0',
  },
  {
    id: 'TC075',
    module: 'Signup Page',
    scenario: 'Signup mobile number validation',
    steps: [
      'Navigate to signup page',
      'Click mobile number input field',
      'Enter invalid mobile number',
      'Verify validation error is displayed',
      'Enter valid 10-digit mobile number',
      'Verify no validation error',
    ],
    expected: 'Mobile number field validates input format correctly',
    priority: 'P0',
  },
];
